### ISSUE TITLE
Create "Who is using Standard?" Page

### ISSUE THREAD

**Issue by Flet** [standard/standard-www#1]
As suggested in feross/standard#169, we should have a page that showcases projects that are using `standard`!

Should we use all of the repositories listed in [clone.js](https://github.com/feross/standard/blob/master/test/clone.js)? Or should we pick some interesting projects and highlight them? Or a combination of both?

**Comment by feross** [comment]
I like the idea of highlighting interesting projects that are using standard! That sounds like a nice way to direct some attention toward some deserving projects.

But as @jden said, "a lot of javascript adoption happens in cargo-cult fashion based on how popular a thing is perceived to be and how much it looks like a 'real thing'", so I think we need the usual list of companies using `standard`. But showcasing cool or well-known users/projects from the community is a an awesome idea.

If someone can figure out how to do a listing of every module that devDepends on `standard`, I think we could put together quite a cool statistics page that shows the number of npm packages that use `standard`, with a drill-down to see which users and which packages use it. Also, we might discover some users/companies using it who haven't been vocal.

**Comment by Flet** [comment]
Well, this is now covered in the main README itself! Closing.

**Comment by feross** [comment]
🎉
