### ISSUE TITLE
Flow docs incomplete

### ISSUE THREAD

**Issue by cyberwombat** [standard/standard-www#10]
For flow you also need to install `babel-eslint` and use this in package.json:

```
"standard": {
    "parser": "babel-eslint",
    "plugins": [
      "flowtype"
    ]
  }
```

**Comment by Flet** [comment]
Check out this issue on `standard` as its relevant: https://github.com/feross/standard/issues/592

TL;DR: Check out https://github.com/Gozala/standard-flow by @Gozala

Closing this for now, but feel free to comment!
