### ISSUE TITLE
Use Netlify instead of gh-pages

### ISSUE THREAD

**Issue by bcomnes** [standard/standard-www#11]
Has anyone considered using https://www.netlify.com instead of gh-pages?  Its free, supports https custom domains and can run node build scripts on push and do fancy things like PR previews.  I've been really enjoying using it over at the https://github.com/hypermodules/hypermodul.es/blob/master/package.json#L12-L16 website.

**Comment by feross** [comment]
Sounds like the primary benefit is SSL support?

I think GitHub is less likely than Netlify to go out of business in the next 2-5 years. Netlify is a new company who could get acquired or [run out VC funding](https://www.crunchbase.com/organization/netlify) at any point.

That said, if it's trivial to switch to them (and back again if needed), then I'm onboard. Curious what @Flet thinks, since he wrote the majority of the site.

**Comment by Flet** [comment]
Cool, never heard of netlify @bcomnes :) Neat tool!

Yeah SSL would seem to be the biggest difference. Since non-SSL is not causing pain (at the moment) I would prefer not changing things.

With all things trending towards HTTPS, I wonder if GitHub is cooking up a solution for gh-pages.

**Comment by bcomnes** [comment]
HTTPS is a nice gain, even though in practice you don't gain much for a simple static site.  In my eyes, the value is that you can run node.js build scripts (or ruby, or python or perl or go), rather than uploading/committing raw HTML or relying on Jekyll.  This is nice because you can preview changes to the site if they come in on a PR.  The preview link shows up next to other merge checks like travis.  

![screen shot 2017-03-01 at 2 38 24 pm](https://cloud.githubusercontent.com/assets/166301/23484658/bf9a9c0e-fe8c-11e6-9d56-23fbc226bfc9.png)

The only draw back is that it requires someone who maintains the site to have an extra account linked to their GitHub.  Once its set up though, you don't need to mess with it at all and they do have a decent collaborator system:

![screen shot 2017-03-01 at 2 41 17 pm](https://cloud.githubusercontent.com/assets/166301/23484760/275dba1a-fe8d-11e6-8ff8-f21c23842fa9.png)

They could also go out of business at which case we could revert back to gh-pages.  Its only worth it if the gains seem desirable now.

**Comment by feross** [comment]
Cool, thanks for the explanation, seems like a cool product. I defer to @Flet

**Comment by bcomnes** [comment]
I would be willing to set it up, and we can make a decision once its in front of everybody.

**Comment by Flet** [comment]
Cool let's try it @bcomnes!

**Comment by bcomnes** [comment]
Sorry, got super busy at work this week.  Will try to carve some time out this evening.

**Comment by yoshuawuyts** [comment]
Nice, I'm using netlify for my stuff too - works like a charm

**Comment by zeke** [comment]
Didn't know Netlify supported custom build hooks on deploy. That's pretty neat.

The Yarn website is hosted on Netlify and had some downtime issues recently. Hey @thejameskyle, can you shed some light on your experience with the service so far?

**Comment by bcomnes** [comment]
Yes they did have some downtime recently for a couple hours, but hey its free!  I'm going to try to set this up today.

**Comment by jamiebuilds** [comment]
Netlify has been great most of the time. I've had some ongoing issues with language based redirects (although that is currently an enterprise-only feature, which I want them to make available to all open source projects) where people speaking different languages sometimes get 404s.

They also had that downtime which ended up screwing up our builds for several days. Every other build was failing because one of the machines we were running on was screwed up somehow. They did work with me on it though and once they realized what was happening they fixed it immediately.

Overall I think it's a well conceived product which may be a bit immature at this stage. I'm going to keep using it on projects I contribute to. I also hope that GitHub pages steals a number of their features, namely:

- Language-based redirects
- Builds for branches and pull requests
- (In my dreams) a way to have custom deploy scripts & tools
- (Or at least) alternatives to Jekyll, namely https://gohugo.io/

**Comment by bcomnes** [comment]
Ok, I recreated the [master branch](https://github.com/feross/standard-www/tree/master) and pushed my work there, as that is where I recommend things live in this type of setup.  Basically what I did is flatten out the `generate-site` folder into the top level of the repo and adjust the build script to put things into a `./dist` folder.  

Now thats left is for @feross to activate netlify on this repo and set up the build folder to point to `dist` and the build command to be `npm run start`.  Or he can add us as collaborators on the netlify dashboard and we can set that up / monitor in the future if needed. (my email is bcomnes@[gmail dot com]) Unfortunately, I can't seem to activate the service on this repo myself. I only have access to repos in my account and orgs.

I went ahead and made a fork and set up a test over here: https://standard-bcomnes.netlify.com so people can see the results.

The last step is to then change the DNS over.  https://www.netlify.com/docs/custom-domains/

If we decide not to use this service for whatever reason, I still recommend that we switch to this project layout, and use https://github.com/tschaub/gh-pages to deploy the dist folder to the `gh-pages` branch and keep build and raw assets in separate git timelines.

**Comment by zeke** [comment]
> I also hope that GitHub pages steals a number of their features, namely:
> 
> - Language-based redirects
> - Builds for branches and pull requests
> - (In my dreams) a way to have custom deploy scripts & tools
> - (Or at least) alternatives to Jekyll, namely https://gohugo.io/

cc @benbalter and @parkr who work on GitHub's Pages team.

Apologies to @feross and @bcomnes for co-opting this thread :)

**Comment by bcomnes** [comment]
Take it back!  Thrilled to have gh folks in thread :)

**Comment by Flet** [comment]
Nice work @bcomnes! Thanks for being kind while refactoring my funky old code :)

So far this looks really great. I like the idea of using `tschaub/gh-pages` to push to `gh-pages` `master`. We should set this up as a npm script as a backup plan for sure.
:+1: from me!

#zekefanclub in full force on this thread ❤️

**Comment by bcomnes** [comment]
> So far this looks really great. I like the idea of using `tschaub/gh-pages` to push to `gh-pages` `master`. We should set this up as a npm script as a backup plan for sure. 

I can set that up.

**Comment by bcomnes** [comment]
Ok it is done:

https://github.com/feross/standard-www/blob/master/package.json#L39

EDIT: Actually we probably need to ensure a way CNAME makes it way into the dist folder, but I think we should just pick on strategy and roll with it rather than maintain both.

**Comment by feross** [comment]
Sorry I haven't got to this yet. Will do it soon, promise.

**Comment by bcomnes** [comment]
NP. I'll be around this weekend. It will be the easiest thing you do all all week I promise.

**Comment by feross** [comment]
Just set up Netlify. Not too bad!

- Waiting for DNS to propagate before I try to add TLS to the site.
- I added @bcomnes and @Flet as admins. (Lmk if you're a collab and also want access)

@bcomnes If you have time, it would be nice to send a PR to cleanup the GitHub Pages specific stuff.

**Comment by bcomnes** [comment]
Sure thing!

**Comment by feross** [comment]
TLS is now enabled! https://standardjs.com/

**Comment by feross** [comment]
Changed the default branch back to `master` instead of `gh-pages`.

**Comment by zeke** [comment]
👏
