### ISSUE TITLE
Can you add standard-sass to your website ?

### ISSUE THREAD

**Issue by jetiny** [standard/standard-www#16]
Our projects use standard , to lint sass files I make a standalone sass lint tools named [standard-sass](https://github.com/jetiny/standard-sass).

**Comment by feross** [comment]
Hey, cool effort! I think a great place for this is https://github.com/feross/awesome-standard

If you send a PR there, then it will get added to the "ecosystem" section of the website.

**Comment by jetiny** [comment]
Thanks a lot.
