### ISSUE TITLE
Wrong syntax for Node.js API reference's function call

### ISSUE THREAD

**Issue by theNaut1lus** [standard/standard-www#28]
URL: https://standardjs.com/#is-there-a-nodejs-api

Screenshot
<img width="866" alt="Screenshot 2019-03-28 at 10 54 32 PM" src="https://user-images.githubusercontent.com/35738138/55179119-d61d9b00-51ac-11e9-84b3-b8077d762a6f.png">

here in although I understand the reason for making the `standard.lintText()` function to have a bold and large syntax (Heading Syntax) but the whole flow of the website determines that any code block or line is kept in pre-formatted syntax. 

This could be changed so as to have a small introduction instead of just a small `yes` answer and maybe shifting the `standard.lintText()` into pre-formatted syntax to keep consistency

**Comment by LinusU** [comment]
It indeed seems a bit weird that it's a heading, with an anchor link and all...

PRs welcome 👍

**Comment by theNaut1lus** [comment]
@LinusU please review
