### ISSUE TITLE
"Paste your code" online linter

### ISSUE THREAD

**Issue by feross** [standard/standard-www#3]
As @maxogden said:

> I think the site should have a 'paste your code here to check it with standard' thing

Haven't tested it, but `standard` probably works out-of-the-box in the browser. Doing something like what [babel has](https://babeljs.io/repl/) would be cool.

**Comment by Flet** [comment]
Heh, I tinkered on this idea a couple days ago after reading his comment.

I remembered http://eslint.org/demo/ and thought it would not be difficult to re-use what they have... but its a little funky...

This demo page has a custom built `eslint.js` that is generated from their [Makefile](https://github.com/eslint/eslint/blob/master/Makefile.js#L527). I think cloning/installing eslint and running `npm run browserify` is the only way to get this eslint.js file currently.

Also, plugins do not work in the browser, so the `standard` custom rules may be another challenge. This may require a custom build script with a custom `load-rules.js` (which eslint [rewrites](https://github.com/eslint/eslint/blob/master/Makefile.js#L93) when building for the browser)

Reference: 
https://github.com/eslint/eslint/issues/2585

**Comment by Flet** [comment]
Had some fun today :)

http://flet.github.io/standard-demo/

Needs some polishing up, but it works!

**Comment by zeke** [comment]
Nice work, @Flet!

**Comment by Flet** [comment]
Thanks @zeke :)

I did some more work on this today. Now it has the plugin rules working and also has a format button :tada: 

I also mocked it up a bit to make it fit in standardjs.com just to see what it would look like:
http://flet.github.io/standard-demo/
![image](https://cloud.githubusercontent.com/assets/360233/9479559/82e6053a-4b43-11e5-9d84-2b2f7f89e251.png)

**Comment by feross** [comment]
@Flet This is AMAZING! It runs quite fast!

This makes me wonder if there's anything we can do to speed up the CLI? I guess all the sync file reads that `require` does are making it run slowly...

**Comment by xjamundx** [comment]
Yeah this is sweet

**Comment by dcousens** [comment]
@Flet this is awesome.
Would be great to see this being used for bug reports too.

**Comment by feross** [comment]
@flet are all the needed PRs merged so you can deploy this to standardjs.com?

**Comment by Flet** [comment]
Yeah I will button it up tonight and deploy  it :)
Any preference on URL or link title
On Aug 27, 2015 6:44 PM, Feross Aboukhadijeh notifications@github.com wrote:@flet are all the needed PRs merged so you can deploy this to standardjs.com?

**Comment by feross** [comment]
https://babeljs.io/ uses "Try it out". That works for me, but I don't have a strong opinion.

**Comment by Flet** [comment]
OK, its live! :)
http://standardjs.com/demo.html

**Comment by zeke** [comment]
:clap:

**Comment by feross** [comment]
Great work!
