### ISSUE TITLE
Link Breakage 

### ISSUE THREAD

**Issue by Flet** [standard/standard-www#4]
From feross/standard#250 @flying-sheep

> github and whatever you use on http://standardjs.com/ slugify differently:
> 
> the “Never start a line with ( or [ … More details” link points to #automatic-semicolon-insertion-asi, but >on standardjs.com, the actual anchor is #automatic-semicolon-insertion-asi- with a trailing dash.
> 
> you’ll have to fix the code creating the anchors to behave like on github.

**Comment by Flet** [comment]
We're currently using the `generate-md` command of the `md` package to convert markdown to HTML. 

However, they way it creates anchors for Headings does not match up with the way github does it.

I'm currently exploring some alternatives to make the markdown render closer to they way it does for Github. Github uses their own ruby tool `markup` for generating html ([this is the code for generating heading anchors](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb#L35)).

It looks like there is a node clone of this tool here: https://github.com/rlidwka/render-readme
...but it does not render heading anchors correctly :cry:. 

Opened an issue to get more info: rlidwka/render-readme#8

**Comment by zeke** [comment]
@bcoe and I solved this problem on the npmjs.com website, and we consulted GitHub support for advice.

The npm markdown parser is called [marky-markdown](https://github.com/npm/marky-markdown#readme). It has a `prefixHeadingIds` option that adds prefixes to generated IDs to prevent name collisions.

We then use a bit of front-end code and the [hashchange](https://www.npmjs.com/package/hashchange) module to hide those prefixes from the user: https://github.com/npm/newww/blob/ebbe8a3344341b08026d03c67cfe53e541e88283/assets/scripts/deep-links.js -- this is the same technique GitHub uses.

**Comment by Flet** [comment]
@zeke very cool thanks for sharing your insight! This looks like a nice way to keep things insulated.

My main concern is generating the anchor IDs themselves in a way that is consistent with GitHub. The ultimate goal is to be able to have links between markdown pages that work on GitHub's website as well as on the standardjs.com generated site. If the anchor IDs are not generated consistently between the two, then links to sections would not work.

Unfortunately, I see that `marky-markdown` is not consistent with GitHub either when generating anchor IDs.

Here is what I see coming out of `marky-markdown`:

```
> var md = require('marky-markdown')
> md('## test(\n## test)\n## test_\n## test-\n## test=\n').html()
```

``` html
<h2 id="user-content-test" class="deep-link"><a href="#test">test(</a></h2>
<h2 id="user-content-test" class="deep-link"><a href="#test">test)</a></h2>
<h2 id="user-content-test" class="deep-link"><a href="#test">test_</a></h2>
<h2 id="user-content-test" class="deep-link"><a href="#test">test-</a></h2>
<h2 id="user-content-test" class="deep-link"><a href="#test">test=</a></h2>
```

...and here is an example of what GitHub does (pulling from this this [gist](https://gist.github.com/Flet/1f46a2af2f6b3bf378cf)):

``` html
<h2><a id="user-content-test-14" class="anchor" href="#test-14" aria-hidden="true"><span class="octicon octicon-link"></span></a>test(</h2>
<h2><a id="user-content-test-15" class="anchor" href="#test-15" aria-hidden="true"><span class="octicon octicon-link"></span></a>test)</h2>
<h2><a id="user-content-test_" class="anchor" href="#test_" aria-hidden="true"><span class="octicon octicon-link"></span></a>test_</h2>
<h2><a id="user-content-test-" class="anchor" href="#test-" aria-hidden="true"><span class="octicon octicon-link"></span></a>test-</h2>
<h2><a id="user-content-test-16" class="anchor" href="#test-16" aria-hidden="true"><span class="octicon octicon-link"></span></a>test=</h2>
```

The punctuation filtering that `marky-markdown` does relies on `slugg` and on additional regex: `/[<>]/g`. Also `slugg` does some additional massaging like removing a trailing `-`, which deviates from GitHub's behavior.

The other problem is that some IDs become duplicates after being filtered. `marky-markdown` made all the IDs `test`, but GitHub will add a suffix to ensure they are unique ('test', 'test-2', 'test-3').

Switching to use the same regex for filtering that GitHub uses (`/[^\w\- ]/`) and eliminating `slugg` (just replace spaces with dashes) should make `marky-markdown` a lot more consistent.

Following the same pattern for avoiding duplicates would also be great. This is not a concern for `standard-www`, but its a concern for another project I have ( `## C` and `## C++` headings both become `c`, heh).

Perhaps I should propose these changes on `marky-markdown`...

I should also say that my secondary goal is to avoid writing _yet another_ markdown converter. :smile:

**Comment by zeke** [comment]
Yeah you should submit a PR. We did a lot of work to get a fast and non-buggy syntax highlighter into it (https://github.com/atom/highlights), and the `markdown-it` parser it relies on is very fast and CommonMark compliant.

Sadly I no longer have commit bit on marky-markdown but it seems that some of the npm staff have recently started to pay attention to pull requests. I would give it a shot.

**Comment by Flet** [comment]
PR submitted, thanks for the nudge, @zeke :+1:

**Comment by Flet** [comment]
OK this issue is fixed for now... I've switched to using my `bananaslug` marky-markdown branch which resolves the issue. 

Hopefully someday the PR will get merged at `npm/marky-markdown` :(

I'll leave this issue open and light some incense in the PR's honor at my local karate dojo.

**Comment by Flet** [comment]
OK! `marky-markdown` is in quite an awesome state now :) Updated to the latest version and things work very nicely. Closing!

**Comment by feross** [comment]
That's great news!

**Comment by zeke** [comment]
:metal:
