### ISSUE TITLE
rules.html is rendered wrong

### ISSUE THREAD

**Issue by rstacruz** [standard/standard-www#5]
It looks like the multiple blank lines rule is tripping the markdown parser.

![pasted_image_9_29_15__2_46_pm](https://cloud.githubusercontent.com/assets/74385/10156998/d44191ac-66b8-11e5-9e33-50e3526ed747.png)

**Comment by rstacruz** [comment]
maybe you can consider using metalsmith.io + metalsmith-marked?

**Comment by Flet** [comment]
:(

I have a half-finished task of switching to using `marky-markdown`. I'll see if the issue exists there too.

**Comment by jmmendivil** [comment]
this seems related > https://github.com/chjj/marked/issues/645

**Comment by feross** [comment]
@Flet I just got an email from a professor who is using `standard` in his class and asked if we could fix the rules.html rendering. :) Any progress on that?

**Comment by Flet** [comment]
Wow heh :)

I have a wip branch I will get going tonight!

**Comment by feross** [comment]
Nice!

**Comment by Flet** [comment]
ok @feross and @rstacruz this should be fixed up now via https://github.com/feross/standard-www/commit/b904a69fc209ec48dddf515a93b93eff86e2c319

One other note: code snippets now use the atom-dark theme :smiling_imp: 
I think it looks nice, but OK with switching if folks prefer light.

http://standardjs.com

**Comment by feross** [comment]
I love the new theme!

**Comment by Flet** [comment]
OK, this should be fixed!
