### ISSUE TITLE
Link to projects using standard has changed

### ISSUE THREAD

**Issue by qwo** [standard/standard-www#6]
on the index page 

```
To get a better idea, take a look at a sample file written in JavaScript Standard Style, or check out some of the repositories that use standard.
```

https://github.com/feross/standard-packages/blob/master/standard.json

should point to 

https://github.com/feross/standard-packages/blob/master/all.json or .test.json from the looks of it 

https://github.com/feross/standard-www/blob/gh-pages/index.html#L53

**Comment by feross** [comment]
Good catch!
